last update Rental_HUB

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,7 +1,7 @@
-# Используем официальный Python-образ
+
 FROM python:3.11-slim
 
-# Устанавливаем системные зависимости (включая gettext для локализации)
+
 RUN apt-get update && apt-get install -y \
     build-essential \
     default-libmysqlclient-dev \
@@ -9,22 +9,25 @@ RUN apt-get update && apt-get install -y \
     gettext \
     && rm -rf /var/lib/apt/lists/*
 
-# Устанавливаем рабочую директорию
+
 WORKDIR /app
 
-# Устанавливаем Python-зависимости
+
 COPY requirements.txt .
 RUN pip install --no-cache-dir -r requirements.txt gunicorn
 
-# Копируем проект
+
 COPY . .
 
-# Настройки окружения
+
+RUN if [ ! -f .env.dev ]; then echo "ERROR: .env.dev not found!" && exit 1; fi
+
+
 ENV PYTHONDONTWRITEBYTECODE=1
 ENV PYTHONUNBUFFERED=1
 
-# Открываем порт 8000
+
 EXPOSE 8000
 
-# Основная команда запуска
+
 CMD ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]
